### ISSUE TITLE
Swipe away in-app Safari browser makes most UI buttons unresponsive

### ISSUE THREAD

**Issue by FlipABit** [insanj/Submarine-Issues#14]
In iOS 9.2+, you can dismiss an in-app safari window by swiping from left to right. Doing this within Submarine results in an unresponsive UI. Reproduction steps:

1. Enable the in-app Safari option in settings.
2. Tap on a Reddit post that opens an in-app safari window.
3. Swipe from left to right to dismiss it.
4. Tap on any other button or post.

Observed result: all buttons are unresponsive except for the bottom tab bar.

**Comment by insanj** [comment]
This was fixed in beta 1.2, make sure you're signed up for that before making issues! All you have to do is email me using what account you want to use with TestFlight. Thanks, though, all feedback is helpful.

Here's a project I made to reproduce the bug, it's actually 100% on Apple's side! https://github.com/insanj/SafariSwipeReproducer

**Comment by FlipABit** [comment]
Thanks for the info! I've joined beta 1.2 and can still get it to happen. If you use private browsing in safari, then switch to submarine and go through those steps, it still occurs. Sorry you have to clean up Apple's mess :)
